Subscribe
MarekLempart/simply-chocolate-team-no-5 pull request #10
Opened 2023-11-19 19:15 UTC by MMolik

Prośba o sprawdzenie

2023-11-19 21:46 UTC, MarekLempart approved these changes
Jest kilka błędów: brak ";", nie przeliczone na "em" wielkość line-height nie jest przeliczone na proporcje. Poza tym zmiany w "index.html" faktycznie nie były potrzebne, inny sposób zapisania tego samego :)
Ale za to trzeba byłoby skorygować Twojego *.html.
Zatwierdzam to, żeby zobaczyć jak wygląda. A poprawki można zrobić później.

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +    letter-spacing: -0.6px;
tu powinno być przeliczone na "em" - czyli px / font-size: -0.6/20=0,03em

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +    margin: auto;
margin na auto powinien być lewy i prawy, żeby było na środku

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +    line-height: 24px; /* 120% */
powinno być przeliczone 24px/20px=1.2

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +        line-height: 1.16
brak ";"

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +        margin: auto;
jw.

2023-11-19 21:46 UTC, MarekLempart commented on src/css/subscribe.css
> +        margin: auto;
jw;

2023-11-19 21:46 UTC, MarekLempart commented on src/partials/subscribe.html
> +  <body>
Cała treść sekcji powinna być od "<_section_> do <_/section_> plus <_div_> dla modala
reszta jest nie potrzebna

2023-11-19 21:46 UTC, MarekLempart commented on src/partials/subscribe.html
> +    <script src="./js/modal.js"></script>
To powinno być raczej w "index.html""

2023-11-19 21:47 UTC, MarekLempart commented
Zatwierdzam żeby zobaczyć jak to w całości wygląda.

2023-11-19 21:52 UTC, MarekLempart requested changes
Jest konflikt w "mail". Musisz wywalić te adnotację. Plik musi być czysty tylko komendy.

2023-11-20 20:20 UTC, MMolik commented on src/css/subscribe.css
> +    letter-spacing: -0.6px;
ok wszędzie gdzie było line-hight zamiast px dałem wynik=line-height/font-size

2023-11-20 20:20 UTC, MMolik commented on src/css/subscribe.css
> +    margin: auto;
poprawione wszędzie

2023-11-20 20:20 UTC, MMolik commented on src/css/subscribe.css
> +        line-height: 1.16
dodano brakujące ;

2023-11-20 20:21 UTC, MMolik commented on src/partials/subscribe.html
> +  <body>
usunąłem diva w środku section. został tylko div dla modela poza section

2023-11-20 20:21 UTC, MMolik commented on src/partials/subscribe.html
> +    <script src="./js/modal.js"></script>
usunąłem script w subscribe.html i przeniosłem do głównego pliku index.html

2023-11-20 20:23 UTC, MMolik commented
nie do końca rozumiem z czego wynika konflikt w main.css - dodałem tylko: @import url(./subscribe.css); - nie ma nic więcej. Zobaczymy teraz jak ściągnę main i puszczę wątek jeszcze raz do sprawdzenia.

2023-11-20 20:31 UTC, MarekLempart commented
Myślę, że może być problem z aktualną wersję.


pon., 20 lis 2023, 21:23 użytkownik MMolik ***@***.***>
napisał:

> nie do końca rozumiem z czego wynika konflikt w main.css - dodałem tylko:
> @import <https://github.com/import> url(./subscribe.css); - nie ma nic
> więcej. Zobaczymy teraz jak ściągnę main i puszczę wątek jeszcze raz do
> sprawdzenia.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MarekLempart/simply-chocolate-team-no-5/pull/10#issuecomment-1819751184>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCO23KX5B2254V2QXF56BR3YFO35JAVCNFSM6AAAAAA7R6AANGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMJZG42TCMJYGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-20 21:53 UTC, MarekLempart submitted a review, later dismissed
Dobra próbuję połączyć. Mam nadzieję, że będzie ok

2023-11-20 22:00 UTC, merged